### ISSUE TITLE
 TypeError: object.new() takes exactly one argument (the type to instantiate) - SimpleStats Class

### ISSUE THREAD

**Issue by robelasefa** [Bibo-Joshi/ptbstats#99]
# Description 
I'm encountering a `TypeError` when using the `SimpleStats` class from the `ptbstats` package.

The specific error message is:

`TypeError: object.__new__() takes exactly one argument (the type to instantiate)`

* Here's an example of the code causing the error:

```python
register_stats(
        SimpleStats(
            "texts",
            lambda u: bool(u.message and (filters.TEXT & ~filters.COMMAND).check_update(u)),
        ),
        admin_id=ADMIN_USER_CHAT_IDS,
    )
```

# Expected Behavior:

The `SimpleStats` object should be created successfully, allowing me to register a custom statistic for tracking text messages in this case.

# Actual Behavior:

The `TypeError` mentioned above is raised, preventing the creation of the `SimpleStats` object.

# Additional Information:

Python version: 3.12.1
`ptbstats` version: 2.2

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for reaching out. I ran the example in the readme on py3.12 and it worked fine for me. I also checked running with ptb installed to version 21.3 (even though ptbstats  currently requires ~=20.4). Can you show the full traceback that you get?

**Comment by robelasefa** [comment]
Apologies for the delayed response. Here's the terminal output:

```
d:\LDPlayer\LDPlayer7.0\code\ttsbot\bot\callbacks\register.py:924: PTBUserWarning: If 'per_message=False', 'CallbackQueryHandler' 
will not be tracked for every message. Read this FAQ entry to learn more about the per_* settings: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#what-do-the-per_-settings-in-conversationhandler-do.
  registeration_conv_handler = ConversationHandler(
d:\LDPlayer\LDPlayer7.0\code\ttsbot\bot\callbacks\settings.py:442: PTBUserWarning: If 'per_message=False', 'CallbackQueryHandler' 
will not be tracked for every message. Read this FAQ entry to learn more about the per_* settings: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#what-do-the-per_-settings-in-conversationhandler-do.
  settings_conv_handler = ConversationHandler(
Traceback (most recent call last):
  File "d:\LDPlayer\LDPlayer7.0\code\ttsbot\bot\main.py", line 207, in <module>
    main()
  File "d:\LDPlayer\LDPlayer7.0\code\ttsbot\bot\main.py", line 198, in main
    app.run_polling(allowed_updates=Update.ALL_TYPES, close_loop=False)
  File "D:\LDPlayer\LDPlayer7.0\code\ttsbot\venv\Lib\site-packages\telegram\ext\_application.py", line 881, in run_polling 
    return self.__run(
           ^^^^^^^^^^^
  File "D:\LDPlayer\LDPlayer7.0\code\ttsbot\venv\Lib\site-packages\telegram\ext\_application.py", line 1081, in __run      
    loop.run_until_complete(self.post_init(self))
  File "C:\Users\Habte\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "d:\LDPlayer\LDPlayer7.0\code\ttsbot\bot\main.py", line 81, in post_init
    BotStats(
  File "D:\LDPlayer\LDPlayer7.0\code\ttsbot\venv\Lib\site-packages\ptbstats\_basestats.py", line 32, in __new__
    instance = super().__new__(cls, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```

**Comment by robelasefa** [comment]
Apologies for the delayed response. Here's the terminal output:

```
d:\LDPlayer\LDPlayer7.0\code\ttsbot\bot\callbacks\register.py:924: PTBUserWarning: If 'per_message=False', 'CallbackQueryHandler' 
will not be tracked for every message. Read this FAQ entry to learn more about the per_* settings: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#what-do-the-per_-settings-in-conversationhandler-do.
  registeration_conv_handler = ConversationHandler(
d:\LDPlayer\LDPlayer7.0\code\ttsbot\bot\callbacks\settings.py:442: PTBUserWarning: If 'per_message=False', 'CallbackQueryHandler' 
will not be tracked for every message. Read this FAQ entry to learn more about the per_* settings: https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#what-do-the-per_-settings-in-conversationhandler-do.
  settings_conv_handler = ConversationHandler(
Traceback (most recent call last):
  File "d:\LDPlayer\LDPlayer7.0\code\ttsbot\bot\main.py", line 207, in <module>
    main()
  File "d:\LDPlayer\LDPlayer7.0\code\ttsbot\bot\main.py", line 198, in main
    app.run_polling(allowed_updates=Update.ALL_TYPES, close_loop=False)
  File "D:\LDPlayer\LDPlayer7.0\code\ttsbot\venv\Lib\site-packages\telegram\ext\_application.py", line 881, in run_polling 
    return self.__run(
           ^^^^^^^^^^^
  File "D:\LDPlayer\LDPlayer7.0\code\ttsbot\venv\Lib\site-packages\telegram\ext\_application.py", line 1081, in __run      
    loop.run_until_complete(self.post_init(self))
  File "C:\Users\Habte\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "d:\LDPlayer\LDPlayer7.0\code\ttsbot\bot\main.py", line 81, in post_init
    BotStats(
  File "D:\LDPlayer\LDPlayer7.0\code\ttsbot\venv\Lib\site-packages\ptbstats\_basestats.py", line 32, in __new__
    instance = super().__new__(cls, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```

**Comment by Bibo-Joshi** [comment]
>   File "d:\LDPlayer\LDPlayer7.0\code\ttsbot\bot\main.py", line 81, in post_init
>     BotStats(

Apparently you are using a custom class `BotStats`. please show how you definde that class

**Comment by robelasefa** [comment]
Here is `BotStats`:

```python
from ptbstats import SimpleStats
from telegram import Update
from telegram.ext import Application, ContextTypes


class BotStats(SimpleStats):
    """Customized statistics class for the bot."""

    async def reply_statistics(self, update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
        """Provides statistics information about the bot for the specified command."""
        await super().reply_statistics(update, context)

    def store_data(self, context: ContextTypes.DEFAULT_TYPE) -> None:
        """Stores statistics data for the current command in bot data."""
        context.bot_data.setdefault("bot_stats", {})[self.command] = self.records

    def load_data(self, app: Application) -> None:
        """Loads statistics data for the current command from bot data if available."""
        self.records = app.bot_data.get("bot_stats", {}).get(self.command, {})
```

**Comment by Bibo-Joshi** [comment]
I can't reproduce the problem with this snippet either.
Moreover, I noticed this:

>   File "D:\LDPlayer\LDPlayer7.0\code\ttsbot\venv\Lib\site-packages\ptbstats\_basestats.py", line 32, in __new__
>    instance = super().__new__(cls, *args, **kwargs)

This doesn't match the ptbstats code on v2.2:

https://github.com/Bibo-Joshi/ptbstats/blob/cdbfe9a314582798edf845457eb62bd11030410e/ptbstats/_basestats.py#L32-L33

Note that there is no `*args, **kwargs` - those variables aren't even defined. If you have made changes to the code of PTBstats locally, I can't help you here.

**Comment by robelasefa** [comment]
You are right! I see that the code in _ basestats.py on my local machine
differs from that in the github repository. but, im completely sure that i
didnt made any changes to ptbstats locally. To be convenient, I simply
uninstalled the package and reinstalled it using 'pip install git+
***@***.***' (as stated on the repo
README), but the code remains the same, which is different from the current
code at the github repo.

**Comment by Bibo-Joshi** [comment]
try adding the `--force` flag

**Comment by robelasefa** [comment]
I just figured out what the problem was. I was attempting to install v2.1 using the code snippet from the README. However, the latest version is v2.2. I fixed the issue by installing the most recent version.
